name: Publish to NPM

on:
  push:
    branches:
      - release

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setting Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Setting up PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Installing dependencies
        run: pnpm i

      - name: Create Release Pull Request or Publish NPM
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run changeset:version
          publish: pnpm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
